### ISSUE TITLE
Test suite fails since 2015-01-25

### ISSUE THREAD

**Issue by eserte** [gfx/mousex-getopt#5] opened 2015-02-02 19:13 UTC
See http://matrix.cpantesters.org/?dist=mousex-getopt;reports=1#sl=7,1 for datetime-sorted list of pass/fail reports.

**Comment by pghmcfc** [comment] 2015-02-05 14:58
This is caused by update of Getopt::Long::Descriptive to 0.099.

See https://github.com/gfx/mousex-getopt/pull/6

**Comment by hartzell** [comment] 2015-04-01 20:25
See [this bug](https://rt.cpan.org/Ticket/Display.html?id=103161) and the [associated gist](https://gist.github.com/hartzell/dc5e258b27d7c976f194) for a patch that addresses this problem.

**Comment by gfx** [comment] 2015-04-02 00:06
Fixed by #6 and released 0.36. Thanks.

**Closed by gfx** 2015-04-02 00:06 UTC
